services:
  db:
    image: ${DOCKERHUB_USERNAME}/study-mysql
    pull_policy: always
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=study
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    image: ${DOCKERHUB_USERNAME}/study-backend
    pull_policy: always
    container_name: backend
    environment:
      - DB_URL=db
    depends_on:
      - db
    restart: always

  nginx:
    image: ${DOCKERHUB_USERNAME}/study-nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  db_data: