FROM nginx:alpine AS build

# nginx.conf 파일을 이미지에 포함
COPY nginx.conf /etc/nginx/conf.d/default.conf

# SSL 인증서 복사
#COPY nginx-selfsigned.crt /etc/nginx/ssl/nginx-selfsigned.crt
#COPY nginx-selfsigned.key /etc/nginx/ssl/nginx-selfsigned.key

EXPOSE 80
ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]