FROM gradle:8.8-jdk17 AS build

#소스코드를 복사할 작업 디렉토리를 생성
WORKDIR /app

#라이브러리 설치에 필요한 파일만 복사
COPY build.gradle settings.gradle ./
RUN gradle dependencies --no-daemon

COPY . /app
RUN gradle clean build --no-daemon -x test

FROM openjdk:17-jdk-slim

WORKDIR /app
COPY --from=build /app/build/libs/*.jar /app/study.jar

EXPOSE 8080
ENTRYPOINT ["java"]
CMD ["-jar", "study.jar", "--spring.profiles.active=prod"]
