services:
  db:
    image: ${DOCKERHUB_USERNAME}/study-mysql
    pull_policy: always
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    image: ${DOCKERHUB_USERNAME}/study-backend
    pull_policy: always
    container_name: backend
    environment:
      - DB_URL=db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
    restart: always

  nginx:
    image: ${DOCKERHUB_USERNAME}/study-nginx
    pull_policy: always
    container_name: nginx
    volumes:
      - /etc/letsencrypt/live/airira.click/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/airira.click/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
