spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
