name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # GitHub Secret에서 Docker Hub 사용자 이름을 가져옵니다.
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # GitHub Secret에서 Docker Hub 액세스 토큰을 가져옵니다.

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          source: docker-compose.yml
          target: /home/ec2-user/

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            
            docker-compose down
            docker-compose up -d
